package projectmanagment;

import java.awt.EventQueue;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;

import projectmanagment.ControleurVueGlobale;
import projectmanagment.Etat;
import projectmanagment.GlobalView;
import projectmanagment.Home;
import projectmanagment.Login;
import projectmanagment.Membre;
import projectmanagment.Project;
import projectmanagment.Projet;
import projectmanagment.Tache;
import projectmanagment.VueGlobale;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hay Info
 */
public class GlobalView extends javax.swing.JFrame {
    private int mouseX, mouseY;
    /**
     * Creates new form GlobalView
     */
    public GlobalView() {
        initComponents();
        /*Calendar calendar = Calendar.getInstance();
        calendar.set(2023, Calendar.MAY, 30);
	Date dateFin = calendar.getTime();
        Projet projet = new Projet("Projet TOB", new Tache("Projet", "", new Date(), new Date(), Etat.EnCours, (Tache) null), new HashSet<Membre>(), "Description du projet", new Date(), dateFin);
	projet.getMembres().add(new Membre("Xavier"));
        projet.getMembres().add(new Membre("Meriem"));
	projet.getMembres().add(new Membre("Aurélie"));
        VueGlobale vue = new VueGlobale(projet);
	ControleurVueGlobale controleurG = new ControleurVueGlobale(projet,vue);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rootAccount = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        minimize = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bodyAccount = new projectmanagment.RoundPanel();
        menuBar = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        overview = new javax.swing.JButton();
        projects = new javax.swing.JButton();
        account = new javax.swing.JButton();
        signOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        rootAccount.setBackground(new java.awt.Color(255, 255, 255));
        rootAccount.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(88, 101, 242)));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.setPreferredSize(new java.awt.Dimension(920, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_20px.png"))); // NOI18N

        jPanel9.setOpaque(false);
        jPanel9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel9MouseDragged(evt);
            }
        });
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel9MousePressed(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimize.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        minimize.setForeground(new java.awt.Color(87, 78, 213));
        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_subtract_15px_1.png"))); // NOI18N
        minimize.setBorder(null);
        minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        minimize.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        jPanel9.add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 2, 20, 20));

        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("Search");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        jTextField1.setPreferredSize(new java.awt.Dimension(64, 35));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_male_user_30px_2.png"))); // NOI18N

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(416, 416, 416)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout bodyAccountLayout = new javax.swing.GroupLayout(bodyAccount);
        bodyAccount.setLayout(bodyAccountLayout);
        bodyAccountLayout.setHorizontalGroup(
            bodyAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 774, Short.MAX_VALUE)
        );
        bodyAccountLayout.setVerticalGroup(
            bodyAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        menuBar.setBackground(new java.awt.Color(88, 101, 242));
        menuBar.setPreferredSize(new java.awt.Dimension(240, 680));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_team_builder_90px_1.png"))); // NOI18N

        exit.setBackground(new java.awt.Color(87, 100, 241));
        exit.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 255, 255));
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_white.png"))); // NOI18N
        exit.setText("Exite");
        exit.setBorder(null);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        overview.setBackground(new java.awt.Color(88, 101, 242));
        overview.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        overview.setForeground(new java.awt.Color(255, 255, 255));
        overview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_overview_30px_9.png"))); // NOI18N
        overview.setText("Overview");
        overview.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        overview.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        overview.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        overview.setIconTextGap(15);
        overview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overviewActionPerformed(evt);
            }
        });

        projects.setBackground(new java.awt.Color(88, 101, 242));
        projects.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        projects.setForeground(new java.awt.Color(255, 255, 255));
        projects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_project_30px.png"))); // NOI18N
        projects.setText("Projects");
        projects.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        projects.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        projects.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        projects.setIconTextGap(15);
        projects.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectsActionPerformed(evt);
            }
        });

        account.setBackground(new java.awt.Color(88, 101, 242));
        account.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        account.setForeground(new java.awt.Color(255, 255, 255));
        account.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_search_account_30px.png"))); // NOI18N
        account.setText("Account");
        account.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        account.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        account.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        account.setIconTextGap(15);
        account.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountActionPerformed(evt);
            }
        });

        signOut.setBackground(new java.awt.Color(88, 101, 242));
        signOut.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        signOut.setForeground(new java.awt.Color(255, 255, 255));
        signOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_logout_30px.png"))); // NOI18N
        signOut.setText("Sign out");
        signOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 20, 1, 1));
        signOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        signOut.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        signOut.setIconTextGap(15);
        signOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuBarLayout = new javax.swing.GroupLayout(menuBar);
        menuBar.setLayout(menuBarLayout);
        menuBarLayout.setHorizontalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(account, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(signOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(overview, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
            .addComponent(projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuBarLayout.setVerticalGroup(
            menuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuBarLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel12)
                .addGap(49, 49, 49)
                .addComponent(overview, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(projects, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(account, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208)
                .addComponent(signOut, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(exit)
                .addContainerGap())
        );

        javax.swing.GroupLayout rootAccountLayout = new javax.swing.GroupLayout(rootAccount);
        rootAccount.setLayout(rootAccountLayout);
        rootAccountLayout.setHorizontalGroup(
            rootAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootAccountLayout.createSequentialGroup()
                .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(rootAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE)
                    .addGroup(rootAccountLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bodyAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 834, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 16, Short.MAX_VALUE))))
        );
        rootAccountLayout.setVerticalGroup(
            rootAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootAccountLayout.createSequentialGroup()
                .addGroup(rootAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rootAccountLayout.createSequentialGroup()
                        .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bodyAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menuBar, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(rootAccount, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void jPanel9MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseDragged
        this.setLocation(this.getX() + evt.getX() - this.mouseX, this.getY() + evt.getY() - this.mouseY);
    }//GEN-LAST:event_jPanel9MouseDragged

    private void jPanel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_jPanel9MousePressed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void overviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overviewActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_overviewActionPerformed

    private void projectsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectsActionPerformed
        // TODO add your handling code here:
        Project project = new Project();
        project.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_projectsActionPerformed

    private void accountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountActionPerformed

    private void signOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutActionPerformed
        // TODO add your handling code here:
        Login login = new Login();
        login.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlobalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlobalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlobalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlobalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        Calendar calendar = Calendar.getInstance();
        calendar.set(2023, Calendar.MAY, 30);
	Date dateFin = calendar.getTime();
        Projet projet = new Projet("Projet TOB", new Tache("Projet", "", new Date(), new Date(), Etat.EnCours, (Tache) null), new HashSet<Membre>(), "Description du projet", new Date(), dateFin);
	projet.getMembres().add(new Membre("Xavier"));
        projet.getMembres().add(new Membre("Meriem"));
	projet.getMembres().add(new Membre("Aurélie"));
        VueGlobale vue = new VueGlobale(projet);
	ControleurVueGlobale controleurG = new ControleurVueGlobale(projet,vue);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GlobalView().setVisible(true);
            }
        });
        
        /*EventQueue.invokeLater(new Runnable() {
		public void run() {
                    VueGlobale vue = new VueGlobale(projet);
			ControleurVueGlobale controleurG = new ControleurVueGlobale(projet,vue);
                        
		}
	});*/
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton account;
    private projectmanagment.RoundPanel bodyAccount;
    private javax.swing.JButton exit;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel menuBar;
    private javax.swing.JButton minimize;
    private javax.swing.JButton overview;
    private javax.swing.JButton projects;
    private javax.swing.JPanel rootAccount;
    private javax.swing.JButton signOut;
    // End of variables declaration//GEN-END:variables
}
